### ISSUE TITLE
proxying https 443

### ISSUE THREAD

**Issue by agreif** [fpco/http-reverse-proxy#14]
Hi, 

is it possible to act as a HTTPS server and then reverse proxy to a non-HTTPS app? 

```
browser --- https ---> http-reverse-proxy ----http---> appWithNonHttpsPort
```

If yes, how to configure the certificate and key file in the http-reverse-proxy?

thanks,
Alex.

**Comment by snoyberg** [comment]
It should just be a matter of using warp-tls to run the Application

**Comment by agreif** [comment]
is it also capable of handling multiple subdomains through SNI?

    https://sub1.example.com ----> http-reverse-proxy ----http---> app1
    https://sub2.example.com ----> http-reverse-proxy ----http---> app2
    https://sub3.example.com ----> http-reverse-proxy ----http---> app3

thanks,
Alex.

**Comment by snoyberg** [comment]
I believe so. Information on that would be available in the warp-tls and
tls haddocks.

**Comment by erikd** [comment]
Currently working on something like this myself. Its in this mailing list thread : https://groups.google.com/forum/#!topic/yesodweb/1QlNvouq9kE

**Comment by snoyberg** [comment]
Looks like no action needed here, closing.
