### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by erikd** [fpco/http-reverse-proxy#18]
The docs for [waiProxyTo](https://hackage.haskell.org/package/http-reverse-proxy-0.4.3.1/docs/Network-HTTP-ReverseProxy.html#v:waiProxyTo) say about the first parameter:

> How to reverse proxy. A Left result will be sent verbatim as the response, whereas Right will cause a reverse proxy.

but that first parameter doesn't contain an `Either`.

**Comment by snoyberg** [comment]
I think that whole sentence can just be removed, now that we have an
explicit data constructor instead of borrowing Either.

**Comment by erikd** [comment]
Works for me! Thanks @snoyberg !
