### ISSUE TITLE
EventSource connections

### ISSUE THREAD

**Issue by meteficha** [fpco/http-reverse-proxy#2]
Hey!

After a long time without being able to use `yesod devel`, I've stopped using hsenv and tried to put `yesod devel` to work again.  It seems to be working fine on everything but EventSources.

Using wireshark I was able to see that the app server is correctly returning the event stream.  However, the devel proxy is not returning anything.

It seems that the proxy tries to gunzip the response, so I've tried to set `http-conduit`'s `rawBody` to `True`.  The error persisted.

Any ideas?  If not, I may try to create a simple test case.

**Comment by snoyberg** [comment]
Closing, please reopen if there's more information.
