### ISSUE TITLE
error: missing binary operator before token "("

### ISSUE THREAD

**Issue by gertcuykens** [fpco/http-reverse-proxy#3]
My C pre-processor is struggling with the main test code?

``` haskell
GHCi, version 7.6.3: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.

main.hs:102:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_wai(1, 4, 0)
     ^
phase `C pre-processor' failed (exitcode = 1)
> 
```

If I remove all pre-processor stuff the code runs.

**Comment by simonmichael** [comment]
Ran into this again today. We were getting this when trying to run GHCI in a fresh clone of the project, before doing a build. Doing `stack build` once generates the missing macros, and then GHCI works.

**Comment by simonmichael** [comment]
PS and we were running GHCI with `stack exec -- ghci ARGS..` (to allow loading all packages interpreted). Perhaps `stack ghci` handles this automatically.
