### ISSUE TITLE
`wpsProcessBody` doesn't allow one to read the response body

### ISSUE THREAD

**Issue by krisis** [fpco/http-reverse-proxy#31]
### Background
- I have a reverse proxying WAI application where I wish to log the response body from 'backend' applications when response status is 500 and modify the (outgoing) response body such that the client only sees "Something went wrong".
- The 'backend' applications are designed such that they send the actual exception messages in their response body with status code set to 500.

### Problem
But [`wpsProcessBody`](https://www.stackage.org/haddock/lts-12.13/http-reverse-proxy-0.6.0/Network-HTTP-ReverseProxy.html#v:wpsProcessBody) doesn't give me the actual response body due to `Response ()` in its type signature.

Is there a way to work around this in my reverse proxying application OR should we fix this in this package?

**Comment by snoyberg** [comment]
It's been a while since I've looked at the API, but the `ConduitT` value you return seems like it receives the response body as upstream and sends the new response body downstream.

**Comment by krisis** [comment]
Oops, it never occurred to me that the conduit gives me access to the response body. Thanks for helping me understand how to use the API!

**Comment by snoyberg** [comment]
No problem
