### ISSUE TITLE
WPRModifiedRequest using old style rawpathInfo

### ISSUE THREAD

**Issue by peigongdsd** [fpco/http-reverse-proxy#39]
According to documents of WAI on hackage, we see that WAI recommends to use pathInfo instead of rawPathInfo to modify path in a request. However, this package seems to use rawPathInfo in function  WPRModifiedRequest and WPRModifiedRequestSecure when I try to modify the path info. So is it a historical issues? Is it going to be fixed to support new-style pathInfo?

**Comment by snoyberg** [comment]
http-reverse-proxy is an unusual case of WAI application. This is not a historical issue, but intended behavior. I'm not opposed if you would want to provide an option to use pathInfo instead of rawPathInfo, but it will incur a performance penalty that won't be acceptable for all use cases.

**Comment by peigongdsd** [comment]
Got it, Thanx.
