### ISSUE TITLE
https and change url support for 0.2 release

### ISSUE THREAD

**Issue by gertcuykens** [fpco/http-reverse-proxy#4]
The https ProxyDest I get

Error connecting to gateway:
InvalidStatusLine "\NAK\ETX\NUL\NUL\STX\STX"

1) I would like to proxy 
http://localhost/index.html or https://localhost/index.html to
https://lb1.pcs.ovh.net/v1/AUTH_a4c2ef109c996858a5c3f8e411de8538/gert/index.html

2) If possible redirection to multiple hosts for example 
https://localhost/server1/index.html -> https://server1/index.html
https://localhost/server2/index.html -> https://server2/index.html
https://localhost/server3/index.html -> warp staticApp

**Comment by snoyberg** [comment]
I believe this has been implemented, closing.
