### ISSUE TITLE
Document a rawProxyTo usage example

### ISSUE THREAD

**Issue by jberryman** [fpco/http-reverse-proxy#9]
It would be super helpful to see what a reverse proxy server `main` using `rawProxyTo` looks like. I'm probably being dense, but after clicking around and looking at the source I'm quite confused.

**Comment by snoyberg** [comment]
Does this help? https://github.com/fpco/http-reverse-proxy#raw-example

**Comment by jberryman** [comment]
Ah, thanks so much!
